name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'pnpm'
      - name: Install packages
        run: pnpm install --frozen-lockfile
      - name: Check code formatting
        run: pnpx nx format:check --all
      - name: Run unit tests
        run: pnpx nx test sudogame
